from tkinter import*
import mysql.connector
con=mysql.connector.connect(host="localhost", username="root", password="",database="heyy")
cur=con.cursor()
def save():
    regno=t1.get()
    name=t2.get()
    mark1=t3.get()
    mark2=t4.get()
    mark3=t5.get()
    if regno=='' or name=='' or mark1=='' or mark2=='' or mark3=='':
        print("Please fill all feilds")
    else:
        cur.execute("INSERT INTO student VALUE('%s','%s',%s,%s,%s)" %(regno,name,mark1,mark2,mark3))
        con.commit()
        print("Data Added Success")
def delete():
    regno=t1.get()
    if regno=="":
        print("Please enter the register no")
    else:
        cur.execute("DELETE FROM student WHERE REGNO='%s'"%regno)
        print("delete success")
        con.commit()
def select():
    regno=t1.get()
    if regno=='':
        print('please enter a regno')
    else:
      cur.execute("SELECT *FROM student WHERE REGNO='%s'"%regno)
      result=cur.fetchall()
      for a in result:
          t2.insert(0,a[1])
          t3.insert(0,a[2])
          t4.insert(0,a[3])
          t5.insert(0,a[4])
def update():
        regno=t1.get() 
        name=t2.get()
        mark1=t3.get()
        mark2=t4.get()
        mark3=t5.get()
        cur.execute("UPDATE student SET NAME='%s', mark1=%s, mark2=%s,mark3=%s WHERE regno='%s'" %(name,mark1,mark2,mark3,regno))
        con.commit()
        print("UPDATE SUCCESFULL")
def clear():
    t1.delete(0,END)
    t2.delete(0,END)
    t3.delete(0,END)
    t4.delete(0,END)
    t5.delete(0,END)
root=Tk()
root.title('PYTHON')
root.geometry("720x320")
root.configure(bg="black")
root.iconbitmap("a.ico")
lbl=Label(text="Reg No:", fg="white", bg="black")
lbl1=Label(text="Name  :", fg="white", bg="black")
lbl2=Label(text="Mark1 :", fg="white", bg="black")
lbl3=Label(text="Mark2 :", fg="white", bg="black")
lbl4=Label(text="Mark3 :", fg="white", bg="black")
t1=Entry()
t2=Entry()
t3=Entry()
t4=Entry()
t5=Entry()
t2.place(x=100,y=80)
t1.place(x=100,y=50)
t3.place(x=100,y=110)
t4.place(x=100,y=140)
t5.place(x=100,y=170)
lbl1.place(x=50,y=80)
lbl.place(x=50,y=50)
lbl2.place(x=50,y=110)
lbl3.place(x=50,y=140)
lbl4.place(x=50,y=170)
btn1=Button(text="Save", command=save)
btn=Button(text="Delete", command=delete)
btn2=Button(text="Select", command=select)
btn3=Button(text="Update", command=update)
btn4=Button(text="Clear", command=clear)
btn.place(x=450,y=50)
btn1.place(x=400,y=50)
btn2.place(x=520,y=50)
btn3.place(x=580,y=50)
btn4.place(x=640,y=50)
root.mainloop()
